name: Daily News Trends Word Cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-wordcloud:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests wordcloud matplotlib
    
    - name: Generate Word Cloud
      run: python news_aggregator.py
    
    - name: Commit and Push
      run: |
        mkdir -p output
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/daily_news_trends.png || true
        git commit -m "Update daily news trends word cloud" || echo "No changes to commit"
        git push
